version: "3.8"
services:
  web:
    depends_on:
      - mongo
    build:
      context: ./
      target: dev
    volumes:
      - .:/code
    env_file: ./.env
    command: npm run start:production
    environment:
      - REDIS_HOST=cache
      - REDIS_PORT=$REDIS_DOCKER_PORT
      - DB_HOST=mongo
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
      - NODE_ENV=production
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
  mongo:
    image: mongo:5.0.2
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
  redis:
    image: redis:latest
    container_name: cache
    env_file: ./.env
    environment:
      - ALLOW_EMPTY_PASSWORD=yes # add pw for production
    ports:
      - $REDIS_LOCAL_PORT:$REDIS_DOCKER_PORT
